### ISSUE TITLE
Reuse of ISPD contest codes

### ISSUE THREAD

**Issue by jknechtel** [xinming-wei/SiliconCritic#1]
Great work!

I'm also happy to see that the ISPD contest and scripts enabled your research. However, I'm not happy with the fact that you didn't provide any credit and reference to that. I'd like to kindly request you to add credit and references to the ISPD paper and website to the main README as well as all the files you utilized.

Thanks and best regards,
Johann

**Comment by jknechtel** [comment]
For the record, this is the website I'm referring to: https://wp.nyu.edu/ispd_22_contest/ In particular, the scripts released at https://drive.google.com/file/d/1oz-qoB13UM_LmZcEjIV9gMuinNlxothd/view?usp=sharing are reused here.

**Comment by xinming-wei** [comment]
Hi Johann,

Thank you for bringing this to my attention. I apologize for the oversight. Your work and the resources from the ISPD22 contest have indeed been instrumental in my research, and it was not my intention to neglect giving proper credit.

I have now updated the README file and the relevant source files to include the appropriate acknowledgements and references to the ISPD paper, website, and the scripts. You can find the changes in commit https://github.com/xinming-wei/SiliconCritic/commit/cd11acdd862623e8ca693ecb325a3f885c07b1f7.

I appreciate your understanding and contribution. I hope this resolves the issue, but please let me know if there's anything more I can do.

Best regards,
Xinming

**Comment by jknechtel** [comment]
Thanks Xinming, much appreciated!

Best, Johann
